# Generated by Django 3.2.7 on 2021-09-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data_evento',
            field=models.DateTimeField(),
        ),
    ]
