# Generated by Django 3.2.7 on 2021-10-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick', '0002_alter_event_data_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Cinema', 'Cinema'), ('Teatro', 'Teatro'), ('Sport', 'Sport'), ('Concerti', 'Concerti')], max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='num_ticket',
            field=models.PositiveIntegerField(),
        ),
    ]
