# Generated by Django 3.2.6 on 2021-08-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick', '0003_remove_event_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Cinema', 'Cinema'), ('Teatro', 'Teatro'), ('Sport', 'Sport')], max_length=200, null=True),
        ),
    ]
