# Generated by Django 3.2.6 on 2021-08-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick', '0004_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Cinema', 'Cinema'), ('Teatro', 'Teatro'), ('Sport', 'Sport'), ('Concerti', 'Concerti')], max_length=200, null=True),
        ),
    ]
