# Generated by Django 3.2.7 on 2021-10-04 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick', '0005_alter_event_prezzo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='prezzo',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
