# Generated by Django 3.2.6 on 2021-08-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick', '0005_alter_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='data',
        ),
        migrations.AddField(
            model_name='event',
            name='data_evento',
            field=models.CharField(default='10 marzo', max_length=100),
        ),
    ]
