# Generated by Django 3.2.6 on 2021-08-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick', '0009_alter_event_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='immagine',
            field=models.ImageField(blank=True, default='static/tick/default.png', null=True, upload_to=''),
        ),
    ]
