# Generated by Django 3.2.6 on 2021-08-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick', '0011_alter_event_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='immagine',
            field=models.ImageField(blank=True, default='static/tick/default.jpg', null=True, upload_to='uploads/'),
        ),
    ]
