# Generated by Django 3.2.7 on 2021-09-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick', '0014_alter_event_immagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
